import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootProvider from "./provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import Header from "@/components/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Juniordev203 - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootProvider>
          <div className="m-h-screen">
            <SidebarProvider>
              {/* <AppSidebar /> */}
              <div className="w-full">
                <main className="w-full">
                  {children}
                </main>
              </div>
            </SidebarProvider>
          </div>
        </RootProvider>
      </body>
    </html>
  );
}
